position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg prefix)arm_joint1
    - $(arg prefix)arm_joint2
    - $(arg prefix)arm_joint3
    - $(arg prefix)arm_joint4
    - $(arg prefix)arm_joint5
    - $(arg prefix)arm_joint6
    - $(arg prefix)arm_joint7
  constraints:
    goal_time: 0.5
    $(arg prefix)arm_joint1: { goal: 0.05}
    $(arg prefix)arm_joint2: { goal: 0.05}
    $(arg prefix)arm_joint3: { goal: 0.05}
    $(arg prefix)arm_joint4: { goal: 0.05}
    $(arg prefix)arm_joint5: { goal: 0.05}
    $(arg prefix)arm_joint6: { goal: 0.05}
    $(arg prefix)arm_joint7: { goal: 0.05}

effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - $(arg prefix)arm_joint1
    - $(arg prefix)arm_joint2
    - $(arg prefix)arm_joint3
    - $(arg prefix)arm_joint4
    - $(arg prefix)arm_joint5
    - $(arg prefix)arm_joint6
    - $(arg prefix)arm_joint7
  gains:
    $(arg prefix)arm_joint1: { p: 600, d: 30, i: 0 }
    $(arg prefix)arm_joint2: { p: 600, d: 30, i: 0 }
    $(arg prefix)arm_joint3: { p: 600, d: 30, i: 0 }
    $(arg prefix)arm_joint4: { p: 600, d: 30, i: 0 }
    $(arg prefix)arm_joint5: { p: 250, d: 10, i: 0 }
    $(arg prefix)arm_joint6: { p: 150, d: 10, i: 0 }
    $(arg prefix)arm_joint7: { p: 50, d: 5, i: 0 }
  constraints:
    goal_time: 0.5
    $(arg prefix)arm_joint1: { goal: 0.05}
    $(arg prefix)arm_joint2: { goal: 0.05}
    $(arg prefix)arm_joint3: { goal: 0.05}
    $(arg prefix)arm_joint4: { goal: 0.05}
    $(arg prefix)arm_joint5: { goal: 0.05}
    $(arg prefix)arm_joint6: { goal: 0.05}
    $(arg prefix)arm_joint7: { goal: 0.05}

franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  joint_names:
    - $(arg prefix)arm_joint1
    - $(arg prefix)arm_joint2
    - $(arg prefix)arm_joint3
    - $(arg prefix)arm_joint4
    - $(arg prefix)arm_joint5
    - $(arg prefix)arm_joint6
    - $(arg prefix)arm_joint7
  arm_id: $(arg prefix)arm
