DEMO_RB1_SIM:
- RLC_GOTO -1.42 -1.79 -1.5181
- RLC_PICK robot_cart_laser
- RLC_GOTO 3.53 -2.24 -1.50
- RLC_GOTO 3.51 -3.30 -1.58
- RLC_PLACE
- RLC_GOTO 0.94 2.63 1.53
- RLC_CHARGE
- WAIT 10
- RLC_UNCHARGE
- RLC_GOTO 3.51 -1.5 -1.58
- RLC_PICK robot_cart_laser
- RLC_GOTO -1.42 -3.5 -1.5181
- RLC_PLACE
- RLC_GOTO 0 0 0
GOTO_TEST:
- GOTO 1 0 0
- GOTO 1 2 0
- GOTO -1 0 0
GOTO_TEST2:
- GOTO 3 0 0
- GOTO -3 0 0
- GOTO 2 2 3.14
GOTO_WAIT_FOR_TRUE:
- RLC_GOTO_TAG p2
- WAIT_TRIGGER1 true
- RLC_GOTO_TAG p0
MOVE_TEST:
- 'MOVE 0.2 0 '
- ' WAIT 2 '
- ' MOVE 0.2 0'
TEST_WAIT:
- WAIT 5
carlos_test:
- 'RLC_GOTO_TAG p1 '
- ' WAIT 5'
test:
- RLC_GOTO_TAG p0
- WAIT 1
- RLC_GOTO_TAG p3
test1:
- 'RLC_GOTO_TAG p0 '
- ' WAIT 5 '
- ' RLC_GOTO_TAG p1'
test2:
- RLC_GOTO_TAG p0
- WAIT 1
- RLC_GOTO_TAG p1
test_charge_uncharge:
- 'RLC_CHARGE None '
- ' WAIT 10 '
- ' RLC_UNCHARGE '
- ' RLC_MOVE -0.5 0'
uncharge:
- RLC_UNCHARGE
