# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_arm_joint1
    - robot_arm_joint2
    - robot_arm_joint3
    - robot_arm_joint4
    - robot_arm_joint5
    - robot_arm_joint6
    - robot_arm_joint7
    - robot_gripper_finger1_base_joint
    - robot_gripper_finger1_joint
    - robot_back_left_wheel_joint
    - robot_back_right_wheel_joint
    - robot_front_left_wheel_joint
    - robot_pantilt_pan_joint
    - robot_pantilt_tilt_joint
    - robot_front_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm/effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_arm_joint1
      - robot_arm_joint2
      - robot_arm_joint3
      - robot_arm_joint4
      - robot_arm_joint5
      - robot_arm_joint6
      - robot_arm_joint7