#!/bin/bash
sudo dpkg -i ros-melodic-dh3-urdf_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dh-gripper-msgs_0.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dh-gripper-driver_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dh-pgc140-urdf_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dynamixel-workbench-toolbox_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dynamixel-workbench-controllers_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-dynamixel-workbench-ros-control_0.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-image-filter_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-multimap-server-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures-msgs_1.0.3-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures-test-msgs_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-bringup_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-test_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-simple-command-manager-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-leds-msgs_0.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-move-base_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-msgs_2.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-marker-mapping_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-poi-manager-msgs_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rcomponent_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-battery-estimation_1.1.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-charge-manager_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-base-hw-lib_2.1.2-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-navigation-msgs_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-docker_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-locator_1.0.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-move_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-move-base-flex_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-pad-msgs_0.9.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-pose-filter_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-safety-controller_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-signal-msgs_1.0.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-msgs_1.2.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-velocity-limiter_1.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-waypoints_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-waypoints-bringup_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-waypoints-msgs_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-waypoints-exe_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robotnik-waypoints-manager_0.1.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon-msgs_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon-core_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rqt-rosmon_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-rosmon_2.2.1-0bionic_amd64.deb
sudo dpkg -i ros-melodic-service-shifter_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-procedures_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-procedures_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-components_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-robot-local-control-dummy-components_1.6.0-0bionic_amd64.deb
sudo dpkg -i ros-melodic-xmlrpc-server_0.3.0-0bionic_amd64.deb
